In [189]:
#Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [190]:
#importing the dataset
dataset = pd.read_csv('salary.csv')
dataset.head()

age          workclass  education-num  hrs per week  salary
0   28            Private             13            40   <=50K
1   31            Private             14            50    >50K
2   30          State-gov             13            40    >50K
3   40            Private             16            60    >50K
4   48   Self-emp-not-inc             12            40   <=50K

In [191]:
#Assigning columns as dependent and indepandent variables
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 4].values
X

array([[28, ' Private', 13, 40],
       [31, ' Private', 14, 50],
       [30, ' State-gov', 13, 40],
       ...,
       [38, ' Private', 13, 45],
       [45, ' Local-gov', 12, 48],
       [65, ' Self-emp-not-inc', 15, 60]], dtype=object)

In [192]:
y

array([' <=50K', ' >50K', ' >50K', ..., ' >50K', ' <=50K', ' <=50K'],
      dtype=object)

In [193]:
#Encoding the column with string parameters

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 1] = labelencoder.fit_transform(X[:, 1])
X
#y = labelencoder.fit_transform(y)
#y

array([[28, 2, 13, 40],
       [31, 2, 14, 50],
       [30, 5, 13, 40],
       ...,
       [38, 2, 13, 45],
       [45, 1, 12, 48],
       [65, 4, 15, 60]], dtype=object)

In [194]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray() 
X

array([[ 0.,  0.,  1., ..., 28., 13., 40.],
       [ 0.,  0.,  1., ..., 31., 14., 50.],
       [ 0.,  0.,  0., ..., 30., 13., 40.],
       ...,
       [ 0.,  0.,  1., ..., 38., 13., 45.],
       [ 0.,  1.,  0., ..., 45., 12., 48.],
       [ 0.,  0.,  0., ..., 65., 15., 60.]])

In [195]:
# Avoiding the dummy variable trap
X = X[:, 1:]

In [196]:
#Splitting the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [197]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [198]:
X_train

array([[-0.45641881,  0.89278777, -0.19886685, ..., -0.96721837,
         1.55057632, -0.20806918],
       [-0.45641881, -1.12008703, -0.19886685, ..., -0.37941815,
         1.04753892,  0.99781938],
       [-0.45641881, -1.12008703,  5.02849026, ...,  0.54426791,
        -1.97068544, -0.36885432],
       ...,
       [ 2.19097016, -1.12008703, -0.19886685, ...,  0.88015376,
         0.04146413, -1.33356517],
       [-0.45641881,  0.89278777, -0.19886685, ..., -0.88324691,
        -0.96461066, -0.52963946],
       [-0.45641881, -1.12008703, -0.19886685, ..., -0.96721837,
         1.04753892,  0.99781938]])

In [199]:
y_train

array([' <=50K', ' >50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)

In [200]:
# Applying Logistic regression
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [201]:
# Predicting the test results
y_pred = regressor.predict(X_test)
y_pred

array([' <=50K', ' >50K', ' >50K', ' <=50K', ' <=50K', ' >50K', ' <=50K',
       ' <=50K', ' >50K', ' <=50K', ' <=50K', ' >50K', ' <=50K', ' >50K',
       ' >50K', ' >50K', ' >50K', ' >50K', ' <=50K', ' >50K', ' <=50K',
       ' >50K', ' <=50K', ' >50K', ' <=50K', ' >50K', ' <=50K', ' <=50K',
       ' >50K', ' <=50K', ' <=50K', ' >50K', ' <=50K', ' >50K', ' >50K',
       ' <=50K', ' <=50K', ' <=50K', ' >50K', ' <=50K', ' >50K', ' >50K',
       ' <=50K', ' >50K', ' <=50K', ' <=50K', ' >50K', ' >50K', ' <=50K',
       ' >50K', ' >50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' >50K',
       ' >50K', ' <=50K', ' <=50K', ' >50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' >50K', ' <=50K', ' <=50K', ' <=50K', ' >50K',
       ' <=50K', ' >50K', ' <=50K', ' >50K', ' <=50K', ' <=50K', ' >50K',
       ' >50K', ' <=50K', ' >50K', ' >50K', ' <=50K', ' <=50K', ' >50K',
       ' <=50K', ' >50K', ' <=50K', ' >50K', ' >50K', ' <=50K', ' >50K',
       ' >50K', ' <=50K', ' <=50K', ' <=5

In [202]:
# Compare the predicted value with the test value
y_test

array([' >50K', ' >50K', ' <=50K', ' >50K', ' <=50K', ' <=50K', ' >50K',
       ' >50K', ' <=50K', ' <=50K', ' <=50K', ' >50K', ' <=50K', ' <=50K',
       ' <=50K', ' >50K', ' >50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' >50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' >50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' >50K',
       ' <=50K', ' >50K', ' <=50K', ' >50K', ' >50K', ' <=50K', ' <=50K',
       ' >50K', ' <=50K', ' <=50K', ' <=50K', ' >50K', ' >50K', ' >50K',
       ' >50K', ' >50K', ' <=50K', ' <=50K', ' >50K', ' <=50K', ' <=50K',
       ' >50K', ' <=50K', ' <=50K', ' <=50K', ' >50K', ' >50K', ' <=50K',
       ' <=50K', ' >50K', ' >50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K',
       ' >50K', ' >50K', ' >50K', ' <=50K', ' >50K', ' <=50K', ' >50K',
       ' >50K', ' <=50K', ' <=50K', ' >50K', ' <=50K', ' <=50K', ' <=50K',
       ' >50K', ' >50K', ' >50K', ' >50K', ' >50K', ' >50K', ' <=50K',
       ' <=50K', ' >50K', ' >50K', ' <=50K', ' <

In [203]:
# Predicting the accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.6654589371980676

In [188]:
# Use stepwise elimination to optimize the model accuracy